config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations' }

  get '@:username/:memo_id', to: 'pages#show', as: 'memo_page'
  get '@:username', to: 'pages#user', as: 'user_page'

  resources :memos
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  validates :title, presence: true

  default_scope { where(deleted_at: nil) }

  extend FriendlyId
  friendly_id :slug_candidate, use: :slugged
  # Use Babosa with Friendly/id
  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :vietnamese).to_s
  end

  include AASM
  aasm(column: 'status', no_direct_assignment: true) do
    state :draft, initial: true
    state :published

    event :publish do
      transitions from: :draft, to: :published
    end

    event :unpublish do
      transitions from: :published, to: :draft
    end
  end

  def destroy
    update(deleted_at: Time.now)
  end

  private
  def slug_candidate
    [
      :title,
      [:title, SecureRandom.hex[0, 8]]
    ]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :memos
  validates :username, presence: true, uniqueness: true

  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private
  def record_not_found
    render file: "#{Rails.root}/public/404.html",
      status: :not_found,
      layout: false
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController

  before_action :authenticate_user!
  before_action :find_memo, only: [:edit, :update, :destroy]

  def index
    @memos = current_user.memos.order(created_at: :desc)
  end

  def new
    @memo = current_user.memos.new
  end

  def create
    @memo = current_user.memos.new(memo_params)
    @memo.publish! if params[:publish]

    if @memo.save
      if params[:publish]
        redirect_to memos_path, notice: '筆記成功發表'
      else
        redirect_to edit_memo_path(@memo), notice: "筆記成功儲存"
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @memo.update(memo_params)
      case
      when params[:publish]
	@memo.publish!
	redirect_to memos_path, notice: '筆記成功張貼'
      when params[:unpublish]
	@memo.unpublish!
	redirect_to memos_path, notice: '筆記成功收回'
      else
        redirect_to edit_memo_path(@memo), notice: '筆記已儲存'
      end
    else
      render :edit
    end
  end

  def destroy
    @memo.destroy
    redirect_to memos_path, notice: '筆記成功刪除'
  end

  def show
  end

  private
  def find_memo
    @memo = current_user.memos.friendly.find(params[:id])
  end

  def memo_params
    params.require(:memo).permit(:title, :content)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @memos = Memo.order(created_at: :desc).includes(:user).take(6)
  end

  def show
    @memo = Memo
  end

  def user
    @user = User
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  private

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :intro, :avatar])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  # 免密碼編輯個人資料
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar(user, size= 300)
    image_tag user.avatar.variant(resize: "#{size}x#{size}"), class: 'user-avatar' if user.avatar.attached?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecondMedium</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'shared/frontend/navbar' %>
      <%= render 'shared/frontend/flash' if notice %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/memos/_content.html.erb
<% if memo.errors.any? %>
  <div class="notification is-warning">
    <%= memo.errors.full_messages.to_sentence %>
  </div>
<% end %>

<%= form_for(memo) do |form| %>
  <%= form.label :title, "標題" %>
  <%= form.text_field :title, class: 'input' %>
  <%= form.label :content, "內文" %>
  <%= form.text_area :content, class: 'textarea' %>
  <%= form.submit "儲存筆記", name: 'save', class: 'button is-light' %>
  <%= form.submit "分享筆記", name: 'publish', class: 'button is-info' if memo.may_publish? %>
  <%= form.submit "收回筆記", name: 'unpublish', class: 'button is-warning' if memo.may_unpublish? %>
<% end %>

app/views/memos/edit.html.erb
<h1 class="title">修改筆記</h1>

<%= render 'content', memo: @memo %>

app/views/memos/index.html.erb
<h1 class="title">筆記簿</h1>
<% @memos.each do |memo| %>
  <div class="content">
    <h2 class="title">
      <%= link_to memo.title, edit_memo_path(memo), class: 'has-text-grey-darker' %>
      <%= content_tag :span, '已發佈', class: 'tag is-primary' if memo.published? %>
    </h2>
    <p><%= strip_tags(memo.content).truncate(200) %></p>
    <p>最後編輯於：<%= time_ago_in_words(memo.updated_at) %>前</p>
    <p>
      <%= link_to "編輯", edit_memo_path(memo), class: 'button is-small' %>
      <%= link_to "刪除", memo_path(memo), method: 'delete', class: 'button is-small is-danger', data: {confirm: "確認刪除?"} %>
    </p>
  </div>
  <hr />
<% end %>

app/views/memos/new.html.erb
<h1 class="title">新增筆記</h1>

<%= render 'content', memo: @memo %>

app/views/pages/index.html.erb
      <section class="columns">
        <!-- left -->
        <section class="column">
          <article>
            <figure class="image">
              <img src="https://fakeimg.pl/350x150/f0f0f0" alt="">
            </figure>
            <h2 class="title is-5">Creating a Pipeline to True Workplace Diversity</h2>
            <p class="content">Providing resources, offering acceptance, and involving people of color are keys to making your company more diverse...</p>
            <footer>
              <p>Arielle Wiltz in Modus</p>
              <p>Aug 7</p>
            </footer>
          </article>
        </section>
        <!-- left -->
        <!-- middle -->
        <section class="column">
          <article class="media">
            <figure class="media-left">
              <img src="https://fakeimg.pl/100x100/">
            </figure>
            <div class="media-content">
              <h2 class="title is-5">I Worked for an Amish Reality TV Show</h2>
              <footer>
                <p>Arielle Wiltz in Modus</p>
                <p>Aug 7</p>
              </footer>
            </div>
          </article>
          <article class="media">
            <figure class="media-left">
              <img src="https://fakeimg.pl/100x100/">
            </figure>
            <div class="media-content">
              <h2 class="title is-5">I Worked for an Amish Reality TV Show</h2>
              <footer>
                <p>Arielle Wiltz in Modus</p>
                <p>Aug 7</p>
              </footer>
            </div>
          </article>
          <article class="media">
            <figure class="media-left">
              <img src="https://fakeimg.pl/100x100/">
            </figure>
            <div class="media-content">
              <h2 class="title is-5">I Worked for an Amish Reality TV Show</h2>
              <footer>
                <p>Arielle Wiltz in Modus</p>
                <p>Aug 7</p>
              </footer>
            </div>
          </article>
        </section>
        <!-- middle -->
        <!-- right -->
        <section class="column">
          <article>
            <figure class="image">
              <img src="https://fakeimg.pl/350x200/f0f0f0" alt="">
            </figure>
            <h2 class="title is-5">Creating a Pipeline to True Workplace Diversity</h2>
            <p class="content">Providing resources, offering acceptance, and involving people of color are keys to making your company more diverse...</p>
            <footer>
              <p>Arielle Wiltz in Modus</p>
              <p>Aug 7</p>
            </footer>
          </article>
        </section>
        <!-- right -->
      </section>

      <hr>

      <section class="columns">
        <!-- article list -->
	<section class="column is-two-thirds">
	  <% @memos.each do |memo| %>
          <article class="media">
            <div class="media-content">
  	      <h2 class="title is-4"><%= link_to memo.title, memo_page_path(memo.user.username, memo), class: 'has-text-grey-dark' %></h2>
	      <p class="content"><%= memo.content %></p>
              <footer>
  	        <p><%= link_to memo.user.username, user_page_path(memo.user.username), class: 'has-text-grey-dark' %> in 網路政策 | 最後更新於 <%= time_ago_in_words(memo.updated_at) %>前</p>
              </footer>
            </div>
            <figure class="media-right">
	      <img src="https://fakeimg.pl/150x150/">
            </figure>
	  </article>
	  <% end %>
        </section>
        <!-- article list -->

        <section class="column">
          <h2 class="title is-4">Popular on Medium</h2>
          <hr>

          <article class="media">
            <div class="media-left">01</div>
            <div class="media-content">
              <h3>Difficult Conversation Lessons From a Psychologist Who’s Been Dealing With People</h3>
              <footer>
                <p>Thomas Oppong</p>
              </footer>
            </div>
          </article>

          <article class="media">
            <div class="media-left">02</div>
            <div class="media-content">
              <h3>Difficult Conversation Lessons From a Psychologist Who’s Been Dealing With People</h3>
              <footer>
                <p>Thomas Oppong</p>
              </footer>
            </div>
          </article>

          <article class="media">
            <div class="media-left">03</div>
            <div class="media-content">
              <h3>Difficult Conversation Lessons From a Psychologist Who’s Been Dealing With People</h3>
              <footer>
                <p>Thomas Oppong</p>
              </footer>
            </div>
          </article>

          <article class="media">
            <div class="media-left">04</div>
            <div class="media-content">
              <h3>Difficult Conversation Lessons From a Psychologist Who’s Been Dealing With People</h3>
              <footer>
                <p>Thomas Oppong</p>
              </footer>
            </div>
          </article>

          <article class="media">
            <div class="media-left">05</div>
            <div class="media-content">
              <h3>Difficult Conversation Lessons From a Psychologist Who’s Been Dealing With People</h3>
              <footer>
                <p>Thomas Oppong</p>
              </footer>
            </div>
          </article>
        </section>
      </section>

app/views/shared/frontend/_flash.html.erb
<div class="notification is-primary">
  <%= notice %>
</div>

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to "Second Medium", root_path, class:"navbar-item has-text-weight-bold" %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if user_signed_in? %>
	    <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
	      <%= avatar(current_user,64) %>
	      <%= current_user.email %>
	    </a>
	    <div class="navbar-dropdown">
	      <%= link_to "新增筆記", new_memo_path, class: 'navbar-item' %>
	      <%= link_to "筆記簿", memos_path, class: 'navbar-item' %>
	      <%= link_to "編輯個人資料", edit_user_registration_path, class:"navbar-item" %>
	      <%= link_to "登出", destroy_user_session_path, class:"navbar-item", method: "DELETE", data: {confirm: '確定登出?'} %>
	    </div>
	  <% else %>
            <%= link_to "註冊", new_user_registration_path, class:"button is-primary" %>
            <%= link_to "登入", new_user_session_path, class:"button is-light" %>
	  <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>